name: Test CI

run-name: ${{ github.triggering_actor }} - ${{ github.event.pull_request.title }}

on:
    pull_request:
        branches:
            - develop
            - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install

      - name: Run test
        uses: ArtiomTr/jest-coverage-report-action@v2

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage