name: Test CI

run-name: ${{ github.triggering_actor }} - ${{ github.ref }}

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test